# Generated by Django 2.1.5 on 2019-01-17 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('role', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('primary_skills', models.CharField(max_length=200)),
                ('secondary_skills', models.CharField(max_length=200)),
            ],
        ),
    ]
